name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
            build_type: Release
            compiler_name: msvc
            generator: ""
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
            build_type: Release
            compiler_name: gcc
            generator: "-G Ninja"
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
            build_type: Release
            compiler_name: clang
            generator: "-G Ninja"

    steps:
    - uses: actions/checkout@v4

    - name: Install Ninja (Linux)
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y ninja-build

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        ${{ matrix.generator }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest --build-config ${{ matrix.build_type }} --output-on-failure

    - name: Upload Binaries
      uses: actions/upload-artifact@v4
      with:
        name: studiomdl++-${{ runner.os }}-${{ matrix.compiler_name }}
        # The ** wildcard ensures we catch files whether they are in /bin/ (Linux) or /bin/Release/ (Windows)
        path: |
          ${{ steps.strings.outputs.build-output-dir }}/bin/**/*
          !${{ steps.strings.outputs.build-output-dir }}/bin/**/*.pdb
        if-no-files-found: error
